import { GameMode } from "./gameModes";

export type WordItem = {
  word: string;
  hint: string;
};

export const WORDS: Record<GameMode, WordItem[]> = {
  fun: [
    { word: "OCEAN", hint: "Vast body of salt water" },
    { word: "PYRAMID", hint: "Ancient triangular structure in Egypt" },
    { word: "KEYBOARD", hint: "Used to type on a computer" },
    { word: "VOLCANO", hint: "Erupts with lava" },
    { word: "BALLOON", hint: "Filled with air and floats" },
    { word: "TELESCOPE", hint: "Used to see distant stars" },
    { word: "UMBRELLA", hint: "Protects you from rain" },
    { word: "JUNGLE", hint: "Dense forest with wild animals" },
    { word: "ROBOT", hint: "Machine that can perform tasks" },
    { word: "CASTLE", hint: "Home of kings and queens" },
    { word: "DIAMOND", hint: "A very hard precious stone" },
    { word: "AIRPLANE", hint: "Flies in the sky carrying passengers" },
    { word: "CAMERA", hint: "Used to take photos" },
    { word: "BICYCLE", hint: "Two-wheeled vehicle you pedal" },
    { word: "RAINBOW", hint: "Colorful arc after rain" },
    { word: "MAGNET", hint: "Attracts iron objects" },
    { word: "PUZZLE", hint: "Game that tests your thinking" },
    { word: "SATELLITE", hint: "Orbits around a planet" },
    { word: "TORCH", hint: "Portable light source" },
    { word: "CLOCK", hint: "Shows time" },
    { word: "ABERRATION", hint: "A deviation from what is normal" },
    { word: "OBFUSCATE", hint: "To deliberately make something unclear" },
    { word: "QUINTESSENTIAL", hint: "The most perfect example of something" },
    { word: "EPHEMERAL", hint: "Lasting for a very short time" },
    { word: "LABYRINTH", hint: "A complicated maze-like structure" },
    { word: "SERENDIPITY", hint: "Finding something good by chance" },
    { word: "MELLIFLUOUS", hint: "Sweet or musical sounding" },
    { word: "CATASTROPHE", hint: "A sudden great disaster" },
    { word: "PARADOX", hint: "A statement that contradicts itself but may be true" },
    { word: "EUPHEMISM", hint: "Mild word used instead of a harsh one" },
    { word: "ZEALOUS", hint: "Having strong enthusiasm" },
    { word: "AMBIGUOUS", hint: "Open to more than one interpretation" },
    { word: "INSCRUTABLE", hint: "Impossible to understand or interpret" },
    { word: "PERSPICACIOUS", hint: "Having sharp insight or understanding" },
    { word: "UBIQUITOUS", hint: "Present everywhere at once" },
    { word: "NOSTALGIA", hint: "Longing for the past" },
    { word: "CACOPHONY", hint: "Harsh mixture of sounds" },
    { word: "ELOQUENT", hint: "Fluent and persuasive in speaking" },
    { word: "RESILIENT", hint: "Able to recover quickly from difficulties" },
    { word: "TENACIOUS", hint: "Very determined and persistent" },
  ],
  spicy: [
    { word: "GLIMMER", hint: "A faint or unsteady light" },
    { word: "WHISPER", hint: "To speak very softly" },
    { word: "BREEZE", hint: "A gentle wind" },
    { word: "SHADOW", hint: "Dark shape formed by blocking light" },
    { word: "SPARKLE", hint: "To shine with small flashes of light" },
    { word: "MYSTERY", hint: "Something difficult to understand or explain" },
    { word: "JOURNEY", hint: "Travel from one place to another" },
    { word: "FORTUNE", hint: "Luck or wealth" },
    { word: "ECHO", hint: "Sound reflected back" },
    { word: "DRIFT", hint: "To move slowly without direction" },
    { word: "SHIMMER", hint: "To shine with a soft trembling light" },
    { word: "TWILIGHT", hint: "Time between day and night" },
    { word: "RIPPLE", hint: "Small wave on water" },
    { word: "FRAGMENT", hint: "A small broken piece" },
    { word: "WANDER", hint: "To move without a fixed path" },
    { word: "MIRROR", hint: "Reflective surface" },
    { word: "FLUTTER", hint: "Quick light movement" },
    { word: "GLANCE", hint: "A quick look" },
    { word: "RADIANT", hint: "Bright and glowing" },
    { word: "SILHOUETTE", hint: "Dark outline of a figure" },
    { word: "OBSTINATE", hint: "Stubbornly refusing to change opinion" },
    { word: "LUCID", hint: "Expressed clearly and easy to understand" },
    { word: "ARCANE", hint: "Understood by few; mysterious" },
    { word: "IMPECCABLE", hint: "Flawless or perfect" },
    { word: "VORACIOUS", hint: "Having a huge appetite" },
    { word: "RETICENT", hint: "Not revealing thoughts easily" },
    { word: "CANDOR", hint: "Honesty and openness" },
    { word: "DEFERENCE", hint: "Respectful submission to others" },
    { word: "ENIGMA", hint: "A puzzling or mysterious person or thing" },
    { word: "FASTIDIOUS", hint: "Very attentive to detail" },
    { word: "HAPHAZARD", hint: "Lacking any obvious plan" },
    { word: "INDIGNANT", hint: "Feeling anger at unfair treatment" },
    { word: "JUXTAPOSE", hint: "Place side by side for contrast" },
    { word: "KINETIC", hint: "Relating to motion" },
    { word: "LAMENT", hint: "To express deep sorrow" },
    { word: "METICULOUS", hint: "Extremely careful and precise" },
    { word: "NOVICE", hint: "A beginner" },
    { word: "OMINOUS", hint: "Giving the impression something bad will happen" },
    { word: "PRAGMATIC", hint: "Dealing with things realistically" },
    { word: "QUELL", hint: "To suppress or put an end to" },
  ]
};