import { GameMode } from "./gameModes";

export const DARES: Record<GameMode, string[]> = {
  fun: [
  "🐔 Do your best chicken dance for 30 seconds!",
  "🎤 Sing a romantic song in a funny voice!",
  "😂 Try to make your partner laugh in 20 seconds!",
  "🕺 Do a dramatic slow-motion walk across the room!",
  "🤪 Make the ugliest face you can until your partner laughs!",
  "🎭 Act like you're proposing to your partner in the funniest way!",
  "🐒 Copy your partner’s gestures for the next 30 seconds!",
  "🎬 Recreate a famous movie scene together in a silly way!",
  "🗣️ Talk in a baby voice for the next 1 minute!",
  "💃 Dance with no music like nobody’s watching!",
  "📸 Take the funniest selfie together right now!",
  "😂 Laugh continuously for 20 seconds (even if it’s fake)!",
  "🎤 Rap about your partner for 30 seconds!",
  "🤹 Pretend to be a clown and entertain your partner!",
  "😎 Walk like a superstar while your partner hypes you up!",
  "🎭 Act like your partner for 1 minute!",
  "🐧 Walk like a penguin together across the room!",
  "🗨️ Speak only in rhymes for the next 2 minutes!",
  "🤣 Tell the worst joke you know and try to make it funny!",
  "🎉 Celebrate something random like you just won an award!",
    "🎤 Sing a song while your partner acts as your backup dancer!",
  "😂 Try to hold a straight face while your partner makes funny faces!",
  "🕺 Do a couple dance together without any music!",
  "🎭 Act like you're in a soap opera scene together!",
  "🐸 Speak like a frog for the next 1 minute!",
  "🤪 Switch personalities with your partner for 2 minutes!",
  "📸 Take a ‘model photoshoot’ picture together!",
  "🎬 Act like you're in a horror movie together!",
  "😂 Try to make each other laugh by only using weird noises!",
  "🐢 Walk in slow motion like turtles together!",
  "🎤 Give a funny speech about why your partner is amazing!",
  "😆 Do your best evil villain laugh!",
  "🎭 Pretend you're meeting each other for the first time!",
  "🕶️ Act like super cool strangers flirting awkwardly!",
  "🐱 Meow instead of talking for the next 1 minute!",
  "🎉 Throw an imaginary party and dance like crazy!",
  "😂 Try to say tongue twisters to each other without laughing!",
  "🎬 Recreate a cringe romantic scene intentionally badly!",
  "🤹 Pretend you're hosting a funny TV show together!",
  "😎 Do your best slow-motion ‘entry scene’ together!"
],
  spicy: [
 "😉 Maintain intense eye contact with your partner for 30 seconds!",
  "😘 Give your partner a slow forehead kiss!",
  "💞 Hold your partner’s hand and describe what you love about them!",
  "😏 Whisper something flirty in your partner’s ear!",
  "🔥 Compliment your partner in the most seductive tone you can!",
  "😍 Hug your partner tightly for 20 seconds without speaking!",
  "💋 Give your partner 3 quick kisses anywhere (keep it cute)!",
  "🤭 Sit close and don’t break eye contact until one of you laughs!",
  "😜 Say something bold but sweet to your partner!",
  "💃 Do a slow romantic dance together!",
  "😏 Trace your partner’s hand slowly with your fingers!",
  "💖 Describe your partner like you're in a romantic movie!",
  "😘 Give a surprise cheek kiss!",
  "😉 Play with your partner’s hair gently for 20 seconds!",
  "😈 Tell your partner what makes them irresistible!",
  "💞 Hold each other and sway like you're dancing without music!",
  "😍 Say your partner’s name in the most romantic way possible!",
  "🔥 Get close and whisper your favorite memory together!",
  "😏 Pretend you're flirting for the first time!",
  "💋 Blow a kiss and then come closer slowly!",
   "🔥 Get very close to your partner and whisper something bold in their ear!",
  "😏 Maintain eye contact while slowly moving closer until you're inches apart!",
  "💋 Give your partner a slow kiss on the hand and hold it there for a moment!",
  "😉 Describe what you find most attractive about your partner in a seductive tone!",
  "🔥 Sit on your partner’s lap for 30 seconds without breaking eye contact!",
  "😈 Slowly trace your fingers along your partner’s arm while looking at them!",
  "💞 Pull your partner close and hold them like a romantic movie scene!",
  "😏 Pretend you're trying to impress your partner on a first date (very flirty)!",
  "🔥 Whisper your favorite thing about being with your partner!",
  "😍 Slowly brush your partner’s hair back while looking into their eyes!",
  "💋 Get close and almost kiss… but stop at the last second!",
  "😈 Tell your partner what makes them hard to resist!",
  "🔥 Hold your partner’s chin gently and make intense eye contact!",
  "😉 Slowly walk toward your partner like a dramatic romantic scene!",
  "💞 Wrap your arms around your partner from behind!",
  "😏 Say something confidently flirty that would make them blush!",
  "🔥 Sit close, knees touching, and don’t move for 30 seconds!",
  "💋 Give your partner a soft kiss on the cheek and linger!",
  "😈 Look at your partner from head to toe and compliment them boldly!",
  "🔥 Recreate a passionate movie moment in your own style!"
  ]
};